[package]
name = "paint_app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.24.1", features = ["default"] }
winapi = { version = "0.3.9", features = ["winuser", "windef"] }