[package]
name = "text_editor"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27"
syntect = "5.1"
thiserror = "1.0"
unicode-width = "0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
eframe = "0.26.0"
rfd = "0.13.0"